[platformio]
src_dir = src

[env:espclock4]
board = esp32dev
framework = arduino
platform = espressif32
platform_packages = framework-arduinoespressif32 @ https://github.com/cydia2020/framework-arduinoespressif32#main
extra_scripts = ./littlefsbuilder.py
lib_deps = 
  arcao/Syslog @ ^2.0.0
  bblanchon/ArduinoJson @ ^7.4.3
  alanswx/ESPAsyncWiFiManager @ ^0.31
  ESP32Async/ESPAsyncWebServer @ ^3.12.1
upload_speed = 460800
monitor_speed = 115200
